# Generated by Django 4.0.6 on 2022-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RazorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='address',
            field=models.TextField(default='House no 215 Saharanpur Uttar Pradesh India 247001'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='contact',
            field=models.IntegerField(default='9999999999'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='email',
            field=models.EmailField(default='rahulkumar123@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='coffee',
            name='order_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='coffee',
            name='signature_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(default='Rahul Kumar', max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='payment_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
